"""Browser-driven catalog crawler for comix.to (Cloudflare + signed-token API).

comix.to now (a) fronts the site with a Cloudflare Turnstile/managed challenge that a plain HTTP
client can't pass, and (b) gates its ``/api/v1/manga`` JSON API behind a per-request signed ``_``
token generated by obfuscated client JS (changing any param → "Invalid token"). Both defeat the old
raw-httpx API crawler.

The robust path is to let a real, evasion-hardened browser do the work: zendriver passes the
Cloudflare challenge (``Tab.verify_cf``), then we page the server-rendered ``/browse?page=N`` grid —
verified to paginate (28 distinct titles per page, zero overlap) — and read each title card straight
from the DOM (work URL ``/title/<hid>-<slug>`` + cover; title from the card or de-slugged). Enrichment
later fills synopsis/genres/author/popularity from the metadata providers.

This module is runnable STANDALONE so the crawl runs in its own process (the heavy headful browser is
kept out of the app/event loop): it needs an X display, so the caller invokes it under ``xvfb-run``.

  xvfb-run -a -s "-screen 0 1280x1024x24" python -m app.ingestion.comix_browser <start_page> <count>

It prints ``{"cards": [...], "pages": N, "ended": bool}`` as JSON on stdout. ``ended`` is true when a
page returned no cards (catalog exhausted), so the caller can stop advancing.
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import sys

_SITE = "https://comix.to"
_BROWSE = _SITE + "/browse?page={page}"
_CARD_LIMIT_PER_PAGE = 28   # the grid's fixed page size (drives the empty-page end check)

# Extract every distinct /title/<hid>-<slug> card on the page with its cover + best-effort title.
_EXTRACT_JS = r"""(() => {
  const seen = {}, out = [];
  document.querySelectorAll('a[href*="/title/"]').forEach(a => {
    const href = a.getAttribute('href'); if (!href) return;
    const m = href.match(/\/title\/([a-z0-9]+)-(.+?)\/?$/i); if (!m) return;
    const hid = m[1]; if (seen[hid]) return; seen[hid] = 1;
    const img = a.querySelector('img');
    const title = (a.getAttribute('title')
      || a.querySelector('[class*="title"],h1,h2,h3,.name')?.textContent
      || (img && img.getAttribute('alt')) || '').trim();
    const cover = img ? (img.getAttribute('src') || img.getAttribute('data-src') || '') : '';
    out.push({ hid, slug: m[2], title: title.slice(0, 200), cover });
  });
  return JSON.stringify(out);
})()"""


def _chrome_path() -> str | None:
    """Locate a Chrome/Chromium binary: explicit override, else the bundled Playwright build."""
    p = os.environ.get("SHELF_SOLVER_CHROME_PATH", "").strip()
    if p and os.path.isfile(p):
        return p
    roots = [os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "").strip(),
             os.path.expanduser("~/.cache/ms-playwright")]
    for root in roots:
        if not root or not os.path.isdir(root):
            continue
        for dirpath, _dirs, files in os.walk(root):
            if "chrome" in files and "chrome-linux" in dirpath:
                return os.path.join(dirpath, "chrome")
    for cand in ("/usr/bin/google-chrome", "/usr/bin/chromium", "/usr/bin/chromium-browser"):
        if os.path.isfile(cand):
            return cand
    return None


import hashlib

_COVER_MAX_BYTES = 8 * 1024 * 1024


def _localize_cover(url: str, jar: dict, ua: str) -> str | None:
    """Fetch a comix CDN cover through the Cloudflare clearance the browser just earned — comix's CDN
    is CF-gated, so a plain client 403s, but curl_cffi replays cf_clearance with a Chrome TLS
    fingerprint and passes. Store it in the DURABLE /covers/ dir (never LRU-evicted) and return the
    /covers/ URL, or None on failure. Deduped by the url hash so re-crawls don't re-download."""
    if not url or not url.startswith("http"):
        return None
    from .. import covers
    key = hashlib.sha256(url.encode()).hexdigest()[:32]
    existing = covers.existing_cover(key)
    if existing:
        return existing
    try:
        from curl_cffi import requests as creq
        r = creq.get(url, headers={"User-Agent": ua, "Referer": _SITE + "/",
                                   "Accept": "image/avif,image/webp,image/jpeg,image/png,*/*"},
                     cookies=jar, impersonate="chrome", timeout=20)
    except Exception:  # noqa: BLE001
        return None
    ctype = (r.headers.get("content-type") or "").split(";")[0].strip().lower()
    if r.status_code != 200 or not ctype.startswith("image/") or not r.content \
            or len(r.content) > _COVER_MAX_BYTES:
        return None
    return covers.save_cover(key, r.content, ctype)


async def crawl_pages(start_page: int, count: int, *, verbose: bool = False) -> dict:
    """Crawl ``count`` browse pages from ``start_page``. Returns {cards, pages, ended}. Each card's
    CDN cover is fetched through the browser's Cloudflare clearance and stored in /covers/ — so comix
    art (its own cover, not just an AniList fallback) persists durably."""
    import zendriver as zd

    chrome = _chrome_path()
    browser = await zd.start(
        headless=False, sandbox=False, browser_executable_path=chrome,
        browser_args=["--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage",
                      "--disable-software-rasterizer"],
    )
    cards: list[dict] = []
    pages_done = 0
    ended = False
    try:
        tab = await browser.get(_SITE + "/")
        try:
            await tab.verify_cf()
        except Exception as exc:  # noqa: BLE001 — verify_cf is noisy; clearance often lands anyway
            if verbose:
                print(f"verify_cf: {exc!r}", file=sys.stderr)
        await tab.sleep(2)
        # The Cloudflare clearance the browser earned — replayed by curl_cffi to fetch CDN covers.
        ua = ""
        try:
            ua = await tab.evaluate("navigator.userAgent") or ""
        except Exception:  # noqa: BLE001
            pass
        jar = {}
        try:
            jar = {c.name: c.value for c in await browser.cookies.get_all()
                   if c.name in ("cf_clearance", "__cf_bm")}
        except Exception:  # noqa: BLE001
            pass
        for i in range(count):
            page = start_page + i
            await tab.get(_BROWSE.format(page=page))
            await tab.sleep(4)
            try:
                page_cards = json.loads(await tab.evaluate(_EXTRACT_JS))
            except Exception as exc:  # noqa: BLE001
                if verbose:
                    print(f"page {page} extract failed: {exc!r}", file=sys.stderr)
                page_cards = []
            pages_done += 1
            if not page_cards:
                ended = True   # empty page → past the end of the catalog
                break
            # Localize covers through the clearance, CONCURRENTLY (bounded) — curl_cffi is sync so
            # each runs in a thread; doing a page's ~28 covers in parallel keeps the crawl fast.
            if jar.get("cf_clearance"):
                sem = asyncio.Semaphore(8)

                async def _one(card):
                    if not card.get("cover"):
                        return
                    async with sem:
                        local = await asyncio.to_thread(_localize_cover, card["cover"], jar, ua)
                    if local:
                        card["cover"] = local

                await asyncio.gather(*[_one(c) for c in page_cards])
            cards.extend(page_cards)
            if verbose:
                got = sum(1 for c in page_cards if (c.get("cover") or "").startswith("/covers/"))
                print(f"page {page}: {len(page_cards)} cards, {got} covers localized", file=sys.stderr)
    finally:
        try:
            await browser.stop()
        except Exception:  # noqa: BLE001
            pass
    return {"cards": cards, "pages": pages_done, "ended": ended}


def _deslug(slug: str) -> str:
    return re.sub(r"\s+", " ", slug.replace("-", " ")).strip().title()


def normalize_card(card: dict) -> dict | None:
    """A raw DOM card → a stable item: {url, hid, slug, title, cover}. None if unusable."""
    hid = (card.get("hid") or "").strip()
    slug = (card.get("slug") or "").strip().strip("/")
    if not hid or not slug:
        return None
    return {
        "url": f"{_SITE}/title/{hid}-{slug}",
        "hid": hid,
        "slug": slug,
        "title": (card.get("title") or "").strip() or _deslug(slug),
        "cover": (card.get("cover") or "").strip() or None,
    }


async def _main() -> int:
    start = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    count = int(sys.argv[2]) if len(sys.argv) > 2 else 5
    result = await crawl_pages(start, count, verbose=os.environ.get("SHELF_SOLVER_DEBUG") == "1")
    items = [n for n in (normalize_card(c) for c in result["cards"]) if n]
    print(json.dumps({"cards": items, "pages": result["pages"], "ended": result["ended"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(_main()))
