"""Browser-driven catalog crawler for comix.to (Cloudflare + signed-token API).

comix.to now (a) fronts the site with a Cloudflare Turnstile/managed challenge that a plain HTTP
client can't pass, and (b) gates its ``/api/v1/manga`` JSON API behind a per-request signed ``_``
token generated by obfuscated client JS (changing any param → "Invalid token"). Both defeat the old
raw-httpx API crawler.

The robust path is to let a real, evasion-hardened browser do the work: zendriver passes the
Cloudflare challenge (``Tab.verify_cf``), then we page the server-rendered ``/browse?page=N`` grid —
verified to paginate (28 distinct titles per page, zero overlap) — and read each title card straight
from the DOM (work URL ``/title/<hid>-<slug>`` + cover; title from the card or de-slugged). Enrichment
later fills synopsis/genres/author/popularity from the metadata providers.

This module is runnable STANDALONE so the crawl runs in its own process (the heavy headful browser is
kept out of the app/event loop): it needs an X display, so the caller invokes it under ``xvfb-run``.

  xvfb-run -a -s "-screen 0 1280x1024x24" python -m app.ingestion.comix_browser <start_page> <count>

It prints ``{"cards": [...], "pages": N, "ended": bool}`` as JSON on stdout. ``ended`` is true when a
page returned no cards (catalog exhausted), so the caller can stop advancing.
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import sys

_SITE = "https://comix.to"
_BROWSE = _SITE + "/browse?page={page}"
_CARD_LIMIT_PER_PAGE = 28   # the grid's fixed page size (drives the empty-page end check)

# Extract every distinct /title/<hid>-<slug> card on the page with its cover + best-effort title.
_EXTRACT_JS = r"""(() => {
  const seen = {}, out = [];
  document.querySelectorAll('a[href*="/title/"]').forEach(a => {
    const href = a.getAttribute('href'); if (!href) return;
    const m = href.match(/\/title\/([a-z0-9]+)-(.+?)\/?$/i); if (!m) return;
    const hid = m[1]; if (seen[hid]) return; seen[hid] = 1;
    const img = a.querySelector('img');
    const title = (a.getAttribute('title')
      || a.querySelector('[class*="title"],h1,h2,h3,.name')?.textContent
      || (img && img.getAttribute('alt')) || '').trim();
    const cover = img ? (img.getAttribute('src') || img.getAttribute('data-src') || '') : '';
    out.push({ hid, slug: m[2], title: title.slice(0, 200), cover });
  });
  return JSON.stringify(out);
})()"""


def _chrome_path() -> str | None:
    """Locate a Chrome/Chromium binary: explicit override, else the bundled Playwright build."""
    p = os.environ.get("SHELF_SOLVER_CHROME_PATH", "").strip()
    if p and os.path.isfile(p):
        return p
    roots = [os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "").strip(),
             os.path.expanduser("~/.cache/ms-playwright")]
    for root in roots:
        if not root or not os.path.isdir(root):
            continue
        for dirpath, _dirs, files in os.walk(root):
            if "chrome" in files and "chrome-linux" in dirpath:
                return os.path.join(dirpath, "chrome")
    for cand in ("/usr/bin/google-chrome", "/usr/bin/chromium", "/usr/bin/chromium-browser"):
        if os.path.isfile(cand):
            return cand
    return None


import hashlib

_COVER_MAX_BYTES = 8 * 1024 * 1024


def _localize_cover(url: str, jar: dict, ua: str) -> str | None:
    """Fetch a comix CDN cover through the Cloudflare clearance the browser just earned — comix's CDN
    is CF-gated, so a plain client 403s, but curl_cffi replays cf_clearance with a Chrome TLS
    fingerprint and passes. Store it in the DURABLE /covers/ dir (never LRU-evicted) and return the
    /covers/ URL, or None on failure. Deduped by the url hash so re-crawls don't re-download."""
    if not url or not url.startswith("http"):
        return None
    from .. import covers
    key = hashlib.sha256(url.encode()).hexdigest()[:32]
    existing = covers.existing_cover(key)
    if existing:
        return existing
    try:
        from curl_cffi import requests as creq
        r = creq.get(url, headers={"User-Agent": ua, "Referer": _SITE + "/",
                                   "Accept": "image/avif,image/webp,image/jpeg,image/png,*/*"},
                     cookies=jar, impersonate="chrome", timeout=20)
    except Exception:  # noqa: BLE001
        return None
    ctype = (r.headers.get("content-type") or "").split(";")[0].strip().lower()
    if r.status_code != 200 or not ctype.startswith("image/") or not r.content \
            or len(r.content) > _COVER_MAX_BYTES:
        return None
    return covers.save_cover(key, r.content, ctype)


def _poster_url(item: dict) -> str:
    """The best CDN cover URL from an API item's poster object."""
    poster = item.get("poster") if isinstance(item.get("poster"), dict) else {}
    return (poster or {}).get("large") or (poster or {}).get("medium") or ""


async def crawl_pages(start_page: int, count: int, *, verbose: bool = False) -> dict:
    """Crawl ``count`` browse pages from ``start_page``. Returns ``{items, cards, pages, ended}``.

    The comix SPA renders each ``/browse?page=N`` grid by calling its OWN ``/api/v1/manga`` endpoint
    with a per-request signed ``_`` token (which only its obfuscated JS can mint). Rather than forge
    that token, we let the SPA make the call, read the resulting URL (token included) back out of the
    page's ``performance`` resource timing, and simply re-``fetch`` it from inside the page — the
    token stays valid for the session, so this returns the FULL metadata for every card (type, year,
    synopsis, poster, followsTotal/popularity, ratings…), letting ``upsert_item`` rank titles instead
    of stranding them at popularity 0. The DOM scrape is kept as a fallback (``cards``) for any page
    whose API read is missed, so a title is never dropped. Each cover (API poster, else DOM ``img``)
    is localized to durable /covers/ through the Cloudflare clearance the browser earned."""
    import zendriver as zd

    chrome = _chrome_path()
    browser = await zd.start(
        headless=False, sandbox=False, browser_executable_path=chrome,
        browser_args=["--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage",
                      "--disable-software-rasterizer"],
    )
    items: list[dict] = []
    cards: list[dict] = []
    pages_done = 0
    ended = False
    stopped_early = False
    last_page = None
    try:
        tab = await browser.get(_SITE + "/")
        try:
            await tab.verify_cf()
        except Exception as exc:  # noqa: BLE001 — verify_cf is noisy; clearance often lands anyway
            if verbose:
                print(f"verify_cf: {exc!r}", file=sys.stderr)
        await tab.sleep(2)

        # The Cloudflare clearance the browser earned — replayed by curl_cffi to fetch CDN covers.
        ua = ""
        try:
            ua = await tab.evaluate("navigator.userAgent") or ""
        except Exception:  # noqa: BLE001
            pass
        jar = {}
        try:
            jar = {c.name: c.value for c in await browser.cookies.get_all()
                   if c.name in ("cf_clearance", "__cf_bm")}
        except Exception:  # noqa: BLE001
            pass

        for i in range(count):
            page = start_page + i
            await tab.get(_BROWSE.format(page=page))
            await tab.sleep(4)

            # 1) Preferred: re-fetch the SPA's own /api/v1/manga URL for THIS page (full metadata + meta).
            page_items, meta = await _read_api_items(tab, page, verbose=verbose)
            if not page_items:
                # Transient API/timing miss — re-request the page ONCE. This both recovers the rich
                # metadata (so the page doesn't silently fall to the popularity-less DOM path) and
                # avoids mistaking a flaky page for the end of the catalog.
                await tab.get(_BROWSE.format(page=page))
                await tab.sleep(3)
                page_items, meta2 = await _read_api_items(tab, page, verbose=verbose)
                meta = meta or meta2
            if meta and isinstance(meta.get("lastPage"), int):
                last_page = meta["lastPage"]
            # 2) Always also read the DOM as a safety net (covers pages the API read still missed).
            try:
                page_cards = json.loads(await tab.evaluate(_EXTRACT_JS))
            except Exception as exc:  # noqa: BLE001
                if verbose:
                    print(f"page {page} DOM extract failed: {exc!r}", file=sys.stderr)
                page_cards = []
            pages_done += 1
            if not page_items and not page_cards:
                # Empty page. The API meta is the AUTHORITY on whether this is the genuine end —
                # only stop the pass when it confirms we're at/past lastPage (or hasNext is false).
                # Otherwise it's a transient miss mid-catalog: flag stopped_early so the caller retries
                # this exact page next tick instead of FALSELY marking the whole catalog synced/done.
                genuine_end = (last_page is not None and page >= last_page) or \
                    (meta is not None and meta.get("hasNext") is False)
                if genuine_end:
                    ended = True
                else:
                    stopped_early = True
                    if verbose:
                        print(f"page {page} empty but not the end (lastPage={last_page}) — "
                              f"transient; will retry", file=sys.stderr)
                break

            # Cover localization (bounded concurrency): API items use their poster, DOM-only cards
            # (hids the API didn't return) use the card img. curl_cffi is sync → run each in a thread.
            api_hids = {(it.get("hid") or "") for it in page_items}
            fallback_cards = [c for c in page_cards if c.get("hid") and c["hid"] not in api_hids]
            if jar.get("cf_clearance"):
                sem = asyncio.Semaphore(8)

                async def _localize(get_url, set_url):
                    url = get_url()
                    if not url or not url.startswith("http"):
                        return
                    async with sem:
                        local = await asyncio.to_thread(_localize_cover, url, jar, ua)
                    if local:
                        set_url(local)

                jobs = []
                for it in page_items:
                    jobs.append(_localize(lambda it=it: _poster_url(it),
                                          lambda v, it=it: it.__setitem__("_cover", v)))
                for c in fallback_cards:
                    jobs.append(_localize(lambda c=c: c.get("cover"),
                                          lambda v, c=c: c.__setitem__("cover", v)))
                await asyncio.gather(*jobs)

            items.extend(page_items)
            cards.extend(fallback_cards)
            if verbose:
                loc = sum(1 for it in page_items if (it.get("_cover") or "").startswith("/covers/"))
                print(f"page {page}: {len(page_items)} api items ({loc} covers localized), "
                      f"{len(fallback_cards)} dom-only fallback", file=sys.stderr)
    finally:
        try:
            await browser.stop()
        except Exception:  # noqa: BLE001
            pass
    return {"items": items, "cards": cards, "pages": pages_done, "ended": ended,
            "stopped_early": stopped_early, "last_page": last_page}


async def _read_api_items(tab, page: int, *, verbose: bool = False) -> tuple[list[dict], dict | None]:
    """The SPA's /api/v1/manga call for ``page``: find that call's URL (signed ``_`` token and all) in
    the page's ``performance`` resource timing, then re-``fetch`` it from inside the page (the token
    stays valid for the session). Returns ``(items, meta)`` where ``meta`` carries lastPage/hasNext —
    the AUTHORITY on whether the catalog is exhausted (so a transient empty page isn't mistaken for the
    end). ``([], None)`` on any miss — the caller falls back to the DOM and treats it as transient."""
    try:
        url = await tab.evaluate(
            "(performance.getEntriesByType('resource').map(e=>e.name)"
            f".filter(n=>n.indexOf('/api/v1/manga')>=0 && n.indexOf('page={page}&')>=0).pop())||''"
        )
    except Exception as exc:  # noqa: BLE001
        if verbose:
            print(f"page {page} perf lookup failed: {exc!r}", file=sys.stderr)
        url = ""
    if not url:
        return [], None
    js = ("(async()=>{try{const r=await fetch(%s,{headers:{'Accept':'application/json'}});"
          "const j=await r.json();const res=j&&j.result;"
          "return JSON.stringify({items:(res&&res.items)||[], meta:(res&&res.meta)||null});}"
          "catch(e){return JSON.stringify({items:[],meta:null});}})()" % json.dumps(url))
    try:
        raw = await tab.evaluate(js, await_promise=True)
        data = json.loads(raw) if raw else {}
    except Exception as exc:  # noqa: BLE001
        if verbose:
            print(f"page {page} api re-fetch failed: {exc!r}", file=sys.stderr)
        return [], None
    items = [it for it in (data.get("items") or []) if isinstance(it, dict) and it.get("hid")]
    meta = data.get("meta") if isinstance(data.get("meta"), dict) else None
    return items, meta


def _deslug(slug: str) -> str:
    return re.sub(r"\s+", " ", slug.replace("-", " ")).strip().title()


def normalize_card(card: dict) -> dict | None:
    """A raw DOM card → a stable item: {url, hid, slug, title, cover}. None if unusable."""
    hid = (card.get("hid") or "").strip()
    slug = (card.get("slug") or "").strip().strip("/")
    if not hid or not slug:
        return None
    return {
        "url": f"{_SITE}/title/{hid}-{slug}",
        "hid": hid,
        "slug": slug,
        "title": (card.get("title") or "").strip() or _deslug(slug),
        "cover": (card.get("cover") or "").strip() or None,
    }


async def _main() -> int:
    start = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    count = int(sys.argv[2]) if len(sys.argv) > 2 else 5
    result = await crawl_pages(start, count, verbose=os.environ.get("SHELF_SOLVER_DEBUG") == "1")
    # Rich API items (full metadata incl. popularity) pass straight through; DOM-only fallback cards
    # are normalized to the minimal {url, hid, slug, title, cover} shape.
    cards = [n for n in (normalize_card(c) for c in result["cards"]) if n]
    print(json.dumps({"items": result["items"], "cards": cards,
                      "pages": result["pages"], "ended": result["ended"],
                      "stopped_early": result.get("stopped_early", False),
                      "last_page": result.get("last_page")}))
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(_main()))
